### PR TITLE
 Fix in Node 10, closes #10 

### LINKED ISSUE #10: Busted in node 10
I don't have time to dig in at the moment, but this is busted in Node 10

```console
TypeError: list.getEntries is not a function
at parseEntries (/Users/bret/repos/choo-test-app/node_modules/on-performance/index.js:47:10)
at Timeout._onTimeout (/Users/bret/repos/choo-test-app/node_modules/on-performance/index.js:36:5)
at ontimeout (timers.js:427:11)
at tryOnTimeout (timers.js:289:5)
at listOnTimeout (timers.js:252:5)
at Timer.processTimers (timers.js:212:10)
```

https://github.com/nodejs/node/commit/2ec6995555

### PR DESCRIPTION
**Pull request by goto-bus-stop**
- Add a test for a single performance measurement in Node.
- Add Node 10 to CI
- If `perf_hooks.performance` has a global buffer, use it, else don't! This means it should still work in node >=8.5 <10 too

### CODE REVIEW

**Review by bcomnes — APPROVED** [review]
🙏Thanks for fixing this

**Review by yoshuawuyts — APPROVED** [review]

**Comment by goto-bus-stop** [comment]
@yoshuawuyts could you add the package to the choojs npm org please? :bowing_woman:
